import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:cached_network_image/cached_network_image.dart';

import '../../../providers/auth_provider.dart';
import '../../../providers/owner_profile_provider.dart';
import '../../../providers/favorites_provider.dart';
import '../../../providers/scheduled_visits_provider.dart';
import '../../../providers/enquiries_provider.dart';

const _kPrimary = Color(0xFF6C5CE7);
const _kBg = Color(0xFFF9FAFB);
const _kTextDark = Color(0xFF1A1A2E);
const _kTextMid = Color(0xFF6B7280);
const _kBorder = Color(0xFFE5E7EB);

class ProfileScreen extends ConsumerStatefulWidget {
  const ProfileScreen({super.key});

  @override
  ConsumerState<ProfileScreen> createState() => _ProfileScreenState();
}

class _ProfileScreenState extends ConsumerState<ProfileScreen> {
  String _normalizeImage(String raw) {
    final v = raw.trim();
    if (v.isEmpty) return v;
    if (v.startsWith('http://') || v.startsWith('https://')) return v;
    return Uri.parse(
      'https://propertysearch.visionvivante.in',
    ).resolve('/storage/$v').toString();
  }

  Widget _buildStat(String count, String label) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        Text(
          count,
          style: const TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.bold,
            color: _kTextDark,
          ),
        ),
        const SizedBox(height: 4),
        Text(
          label,
          style: const TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.w500,
            color: _kTextMid,
          ),
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    final user = ref.watch(authProvider).user;
    final owner = ref.watch(ownerProfileNotifierProvider).profile;
    final ownerImage = owner == null ? '' : _normalizeImage(owner.imageUrl);
    final rawName = (owner?.name.trim().isNotEmpty ?? false)
        ? owner!.name.trim()
        : (user?.name.trim() ?? '');
    final isAutoName = rawName.toLowerCase().startsWith('user') && RegExp(r'^user[\s_]*\d*$').hasMatch(rawName.toLowerCase());
    final displayName = isAutoName ? '' : rawName;
    final rawEmail = (owner?.email.trim().isNotEmpty ?? false)
        ? owner!.email.trim()
        : ((user == null || user.email.trim().isEmpty)
            ? ''
            : user.email.trim());
    // Hide dummy emails generated by the backend (e.g. 92372173@gmail.com)
    final isAutoEmail = RegExp(r'^\d+@.*').hasMatch(rawEmail);
    final displayEmail = isAutoEmail ? '' : rawEmail;

    final savedCount = ref.watch(favoritesProvider).length;
    final scheduledCount = ref.watch(scheduledVisitsNotifierProvider).maybeWhen(
      data: (list) => list.length,
      orElse: () => 0,
    );
    final enquiriesCount = ref.watch(enquiriesNotifierProvider).maybeWhen(
      data: (list) => list.length,
      orElse: () => 0,
    );

    final isProfileIncomplete =
        (owner?.name.trim().isEmpty ?? true) ||
        (owner?.email.trim().isEmpty ?? true) ||
        (owner?.email.endsWith('@example.com') ?? false);

    return Scaffold(
      backgroundColor: _kBg,
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Top Section with overlapping Stats Card
            Stack(
              clipBehavior: Clip.none,
              children: [
                // Purple Header
                Container(
                  padding: EdgeInsets.only(
                    top: MediaQuery.of(context).padding.top + 16,
                    bottom: 60,
                    left: 20,
                    right: 20,
                  ),
                  decoration: const BoxDecoration(
                    color: _kPrimary,
                    borderRadius: BorderRadius.only(
                      bottomLeft: Radius.circular(24),
                      bottomRight: Radius.circular(24),
                    ),
                  ),
                  child: Column(
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          IconButton(
                            onPressed: () {
                              if (context.canPop()) context.pop();
                            },
                            icon: const Icon(Icons.arrow_back, color: Colors.white),
                          ),
                          const Text(
                            'Profile',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 18,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          IconButton(
                            onPressed: () {},
                            icon: const Icon(Icons.settings_outlined, color: Colors.white),
                          ),
                        ],
                      ),
                      const SizedBox(height: 24),
                      Row(
                        children: [
                          Container(
                            width: 80,
                            height: 80,
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              color: Colors.white.withValues(alpha: 0.2),
                              border: Border.all(
                                color: Colors.white,
                                width: 2,
                              ),
                            ),
                            clipBehavior: Clip.antiAlias,
                            child: ownerImage.isEmpty
                                ? const Icon(
                                    Icons.person_rounded,
                                    color: Colors.white,
                                    size: 40,
                                  )
                                : CachedNetworkImage(
                                    imageUrl: ownerImage,
                                    fit: BoxFit.cover,
                                    errorWidget: (context, url, error) =>
                                        const Icon(
                                      Icons.person_rounded,
                                      color: Colors.white,
                                      size: 40,
                                    ),
                                  ),
                          ),
                          const SizedBox(width: 16),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                if (displayName.isNotEmpty) ...[
                                  Text(
                                    displayName,
                                    style: const TextStyle(
                                      color: Colors.white,
                                      fontSize: 18,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                  const SizedBox(height: 4),
                                ],
                                if (displayEmail.isNotEmpty) ...[
                                  Text(
                                    displayEmail,
                                    style: TextStyle(
                                      color: Colors.white.withValues(alpha: 0.85),
                                      fontSize: 13,
                                    ),
                                  ),
                                  const SizedBox(height: 2),
                                ],
                                Text(
                                  '+91 95924 91222', // Mocked as in design
                                  style: TextStyle(
                                    color: Colors.white.withValues(alpha: 0.85),
                                    fontSize: 13,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
                // Overlapping Stats Card
                Positioned(
                  bottom: -30,
                  left: 24,
                  right: 24,
                  child: Container(
                    padding: const EdgeInsets.symmetric(vertical: 20),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(16),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withValues(alpha: 0.04),
                          blurRadius: 10,
                          offset: const Offset(0, 4),
                        ),
                      ],
                    ),
                    child: Row(
                      children: [
                        Expanded(child: _buildStat('$savedCount', 'Saved')),
                        Container(width: 1, height: 30, color: _kBorder),
                        Expanded(child: _buildStat('$scheduledCount', 'Scheduled')),
                        Container(width: 1, height: 30, color: _kBorder),
                        Expanded(child: _buildStat('$enquiriesCount', 'Enquiries')),
                      ],
                    ),
                  ),
                ),
              ],
            ),
            
            const SizedBox(height: 50),

            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 24),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Complete Profile Banner
                  if (isProfileIncomplete)
                    GestureDetector(
                      onTap: () => context.push('/profile/edit'),
                      child: Container(
                        margin: const EdgeInsets.only(bottom: 24),
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          colors: [Colors.red, Colors.red.shade600],
                          begin: Alignment.topLeft,
                          end: Alignment.bottomRight,
                        ),
                        borderRadius: BorderRadius.circular(16),
                      ),
                      child: Row(
                        children: [
                          Container(
                            padding: const EdgeInsets.all(8),
                            decoration: const BoxDecoration(
                              color: Colors.white,
                              shape: BoxShape.circle,
                            ),
                            child: Icon(
                              Icons.priority_high_rounded,
                              color: Colors.red,
                              size: 20,
                            ),
                          ),
                          const SizedBox(width: 16),
                          const Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  'Complete Profile',
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontWeight: FontWeight.bold,
                                    fontSize: 16,
                                  ),
                                ),
                                SizedBox(height: 2),
                                Text(
                                  'Update your name and email to continue.',
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 13,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),

                  const Text(
                    'General',
                    style: TextStyle(
                      color: _kTextDark,
                      fontWeight: FontWeight.bold,
                      fontSize: 15,
                    ),
                  ),
                  const SizedBox(height: 12),
                  Container(
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(20),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withValues(alpha: 0.02),
                          blurRadius: 10,
                          offset: const Offset(0, 4),
                        ),
                      ],
                    ),
                    clipBehavior: Clip.antiAlias,
                    child: Column(
                      children: [
                        _SettingsTile(
                          icon: Icons.person_outline_rounded,
                          title: 'Edit Profile',
                          onTap: user == null
                              ? null
                              : () => context.push('/profile/edit'),
                        ),
                        _SettingsTile(
                          icon: Icons.support_agent_rounded,
                          title: 'Property Enquiries',
                          onTap: () => context.push('/leads'),
                        ),
                        _SettingsTile(
                          icon: Icons.favorite_border_rounded,
                          title: 'Saved Properties',
                          onTap: () => context.push('/favorites'),
                        ),
                        _SettingsTile(
                          icon: Icons.calendar_month_outlined,
                          title: 'My Scheduled Visits',
                          onTap: () => context.push('/scheduled-visits'),
                        ),
                      ],
                    ),
                  ),

                  const SizedBox(height: 32),
                  const Text(
                    'Security',
                    style: TextStyle(
                      color: _kTextDark,
                      fontWeight: FontWeight.bold,
                      fontSize: 15,
                    ),
                  ),
                  const SizedBox(height: 12),
                  Container(
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(20),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withValues(alpha: 0.02),
                          blurRadius: 10,
                          offset: const Offset(0, 4),
                        ),
                      ],
                    ),
                    clipBehavior: Clip.antiAlias,
                    child: Column(
                      children: [
                        _SettingsTile(
                          icon: Icons.shield_outlined,
                          title: 'Change Password',
                          onTap: user == null
                              ? null
                              : () => context.push('/profile/change-password'),
                        ),
                        _SettingsTile(
                          icon: Icons.logout_rounded,
                          title: 'Logout',
                          isDestructive: true,
                          onTap: () async {
                            final router = GoRouter.of(context);
                            final confirm = await showModalBottomSheet<bool>(
                              context: context,
                              backgroundColor: Colors.white,
                              shape: const RoundedRectangleBorder(
                                borderRadius: BorderRadius.vertical(
                                  top: Radius.circular(24),
                                ),
                              ),
                              builder: (ctx) => SafeArea(
                                child: Padding(
                                  padding: const EdgeInsets.all(24.0),
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      Container(
                                        width: 50,
                                        height: 5,
                                        decoration: BoxDecoration(
                                          color: _kBorder,
                                          borderRadius: BorderRadius.circular(
                                            10,
                                          ),
                                        ),
                                      ),
                                      const SizedBox(height: 24),
                                      Container(
                                        padding: const EdgeInsets.all(16),
                                        decoration: BoxDecoration(
                                          color: Colors.red.shade50,
                                          shape: BoxShape.circle,
                                        ),
                                        child: Icon(
                                          Icons.logout_rounded,
                                          color: Colors.red.shade400,
                                          size: 32,
                                        ),
                                      ),
                                      const SizedBox(height: 16),
                                      const Text(
                                        'Logout',
                                        style: TextStyle(
                                          fontSize: 20,
                                          fontWeight: FontWeight.bold,
                                          color: _kTextDark,
                                        ),
                                      ),
                                      const SizedBox(height: 8),
                                      const Text(
                                        'Are you sure you want to log out of your account?',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          fontSize: 15,
                                          color: _kTextMid,
                                        ),
                                      ),
                                      const SizedBox(height: 32),
                                      Row(
                                        children: [
                                          Expanded(
                                            child: TextButton(
                                              onPressed: () =>
                                                  Navigator.of(ctx).pop(false),
                                              style: TextButton.styleFrom(
                                                padding:
                                                    const EdgeInsets.symmetric(
                                                      vertical: 16,
                                                    ),
                                                backgroundColor: _kBg,
                                                shape: RoundedRectangleBorder(
                                                  borderRadius:
                                                      BorderRadius.circular(14),
                                                ),
                                              ),
                                              child: const Text(
                                                'Cancel',
                                                style: TextStyle(
                                                  color: _kTextDark,
                                                  fontWeight: FontWeight.bold,
                                                  fontSize: 16,
                                                ),
                                              ),
                                            ),
                                          ),
                                          const SizedBox(width: 16),
                                          Expanded(
                                            child: ElevatedButton(
                                              onPressed: () =>
                                                  Navigator.of(ctx).pop(true),
                                              style: ElevatedButton.styleFrom(
                                                padding:
                                                    const EdgeInsets.symmetric(
                                                      vertical: 16,
                                                    ),
                                                backgroundColor:
                                                    Colors.red.shade500,
                                                elevation: 0,
                                                shape: RoundedRectangleBorder(
                                                  borderRadius:
                                                      BorderRadius.circular(14),
                                                ),
                                              ),
                                              child: const Text(
                                                'Yes, Logout',
                                                style: TextStyle(
                                                  color: Colors.white,
                                                  fontWeight: FontWeight.bold,
                                                  fontSize: 16,
                                                ),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            );

                            if (confirm != true) return;

                            await ref.read(authProvider.notifier).logout();
                            if (!mounted) return;
                            router.go('/login');
                          },
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 40),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _SettingsTile extends StatelessWidget {
  final IconData icon;
  final String title;
  final VoidCallback? onTap;
  final bool isDestructive;

  const _SettingsTile({
    required this.icon,
    required this.title,
    this.onTap,
    this.isDestructive = false,
  });

  @override
  Widget build(BuildContext context) {
    final color = isDestructive ? Colors.red.shade400 : _kTextDark;
    final iconBg = isDestructive
        ? Colors.red.shade50
        : _kPrimary.withValues(alpha: 0.08);
    final iconColor = isDestructive ? Colors.red.shade400 : _kPrimary;

    return Material(
      color: Colors.white,
      child: InkWell(
        onTap: onTap,
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
          child: Row(
            children: [
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: iconBg,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Icon(icon, color: iconColor, size: 20),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: Text(
                  title,
                  style: TextStyle(
                    fontWeight: FontWeight.w600,
                    fontSize: 14,
                    color: color,
                  ),
                ),
              ),
              if (onTap != null)
                Icon(
                  Icons.chevron_right_rounded,
                  color: _kTextMid.withValues(alpha: 0.5),
                  size: 20,
                ),
            ],
          ),
        ),
      ),
    );
  }
}
